# Generated by Django 3.0.7 on 2020-06-19 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Критерий оценки',
                'verbose_name_plural': 'Критерии оценки',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование юридического лица')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университет',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Группа пользователей',
                'verbose_name_plural': 'Группы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dtgu.UserGroup', verbose_name='Группа пользователя')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dtgu.University', verbose_name='Университет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль пользователей',
            },
        ),
        migrations.CreateModel(
            name='ParamsMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, null=True)),
                ('value', models.TextField(blank=True, max_length=500, null=True)),
                ('HighOrderParamMark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dtgu.ParamsMarks', verbose_name='Критерий оценки всшего порядка')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dtgu.Marks', verbose_name='Критерий оценки')),
            ],
            options={
                'verbose_name': 'Показатель критерия оценки',
                'verbose_name_plural': 'Показатели критериев оценки',
            },
        ),
    ]
