# Generated by Django 2.2 on 2020-06-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dtgu', '0002_auto_20200619_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramsmarks',
            name='HighOrderParamMark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_dtgu.ParamsMarks', verbose_name='Критерий оценки высшего порядка'),
        ),
    ]
