# Generated by Django 2.2 on 2020-06-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dtgu', '0003_auto_20200619_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_dtgu.University', verbose_name='Университет'),
            preserve_default=False,
        ),
    ]
