# Generated by Django 2.2 on 2020-06-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dtgu', '0004_marks_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Типы оценок',
                'verbose_name_plural': 'Типы оценок',
            },
        ),
    ]
