# Generated by Django 2.2 on 2020-06-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dtgu', '0006_auto_20200620_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='code_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Код спецальности на англ.'),
        ),
    ]
