# Generated by Django 2.2 on 2020-06-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dtgu', '0009_auto_20200620_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramsmarks',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_dtgu.Marks', verbose_name='Критерий оценки'),
        ),
    ]
