# Generated by Django 2.2 on 2020-06-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dtgu', '0010_auto_20200620_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramsmarks',
            name='is_good',
            field=models.BooleanField(blank=True, null=True, verbose_name='Проходит ли по критериям'),
        ),
    ]
