# Generated by Django 2.2 on 2020-06-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dtgu', '0012_paramsmarks_valuemin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Учебные предметы',
                'verbose_name_plural': 'Учебные предметы',
            },
        ),
    ]
