# Generated by Django 2.2 on 2020-06-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dtgu', '0013_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='ip',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Название'),
        ),
    ]
